# Fontes
font_family      JetBrains Mono
font_size        11.0

# Janela e Opacidade
background_opacity 0.8
window_padding_width 10
hide_window_decorations yes

# Cores
background #000000
foreground #ffffff

color0  #0a0a0a
color1  #dfc3c3
color2  #c8d6c8
color3  #aaaaaa
color4  #cccccc
color5  #e8e8e8
color6  #ffffff
color7  #e8e8e8

# variantes bright
color8  #2e2e2e
color9  #888888
color10 #aaaaaa
color11 #cccccc
color12 #e8e8e8
color13 #ffffff
color14 #ffffff
color15 #ffffff

# Desabilitar o bipe chato
enable_audio_bell no
