# Tema <nome> — carregado depois do settings.conf, então sobrescreve o que definir aqui.
# Obrigatório: bordas e gaps. Pode ter também decoration {}, animations {} etc.
general {
    col.active_border   = rgba(ffffffff)
    col.inactive_border = rgba(2e2e2e55)
    border_size         = 2
    gaps_in             = 5
    gaps_out            = 10
}
