# Perfil de Hardware (Gerado pelo script de instalação)
source = ~/.config/hypr/hardware_profile.conf

source = ~/.config/hypr/colors.conf      

# Configurações Modulares
source = ~/.config/hypr/configs/settings.conf
source = ~/.config/hypr/configs/animations.conf
source = ~/.config/hypr/configs/execs.conf

# Regras e Binds
source = ~/.config/hypr/rules/windowrules.conf
source = ~/.config/hypr/rules/binds.conf

