general {
    col.active_border   = rgba(ffffffff)   # branco_puro — janela em foco
    col.inactive_border = rgba(2e2e2e55)   # preto_borda com transparência — inativas
    border_size         = 2
    gaps_in             = 5
    gaps_out            = 10
}