# Tema Teste_Colorido — só para testar os scripts (cores exageradas de propósito)
general {
    col.active_border   = rgba(ff00aaff) rgba(ffe600ff) rgba(00e5ffff) 45deg
    col.inactive_border = rgba(7a00ffaa)
    border_size         = 5
    gaps_in             = 10
    gaps_out            = 25
}
