# Fontes
font_family      JetBrains Mono
font_size        11.0

# Janela e Opacidade
background_opacity 0.8
window_padding_width 10
hide_window_decorations yes

# Desabilitar o bipe chato
enable_audio_bell no

# Cores do tema ativo
include ~/.config/theme/palette/kitty.conf
