# Paleta Tema_Teste — kitty
background #2a0055
foreground #39ff14

color0  #1a0033
color1  #ff0055
color2  #39ff14
color3  #ffe600
color4  #00a2ff
color5  #ff00aa
color6  #00e5ff
color7  #f0f0f0

color8  #7a00ff
color9  #ff5588
color10 #7dff66
color11 #fff27a
color12 #66c7ff
color13 #ff66cc
color14 #7af3ff
color15 #ffffff
